---

# Actions that take place on the main branch,
# driven by external dm-api events.

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# (n/a)
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (n/a)

name: publish

on:
  repository_dispatch:
    types:
      dm-api

env:
  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
  CI_PIPELINE_ID: ${{ github.event.client_payload.CI_PIPELINE_ID }}
  CI_COMMIT_TAG: ${{ github.event.client_payload.CI_COMMIT_TAG }}
  GITLAB_API: https://gitlab.com/api/v4/projects
  GITLAB_API_TOKEN: ${{ secrets.DATA_MANAGER_TOKEN }}
  GITLAB_PROJECT: 20449765
  OPENAPI_FILE: openapi.yaml
  OPENAPI_PATH: app%2Fopenapi

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 16.4.0
    # We pull the OpenAPI file
    # using the CI_COMMIT_TAG of the data manager
    - name: Build and test
      run: |
        curl -H "Private-Token: ${GITLAB_API_TOKEN}" ${GITLAB_API}/${GITLAB_PROJECT}/repository/files/${OPENAPI_PATH}%2F${OPENAPI_FILE}/raw?ref=${CI_COMMIT_TAG} --output ${OPENAPI_FILE}
        tail ${OPENAPI_FILE}
        cat ${OPENAPI_FILE} | wc -l
        sed -i s/'"0.0.0"'/'"'${CI_COMMIT_TAG}'"'/ package.json
        head package.json
        npm ci

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 16.4.0
        registry-url: https://registry.npmjs.org/
    # We pull the OpenAPI file
    # using the CI_COMMIT_TAG of the data manager
    - name: Publish
      run: |
        curl -H "Private-Token: ${GITLAB_API_TOKEN}" ${GITLAB_API}/${GITLAB_PROJECT}/repository/files/${OPENAPI_PATH}%2F${OPENAPI_FILE}/raw?ref=${CI_COMMIT_TAG} --output ${OPENAPI_FILE}
        tail ${OPENAPI_FILE}
        cat ${OPENAPI_FILE} | wc -l
        sed -i s/'"0.0.0"'/'"'${CI_COMMIT_TAG}'"'/ package.json
        head package.json
        npm ci
        npm run build
        cp package.json dist/package.json
        cp README.md dist/README.md
        cp LICENSE dist/LICENSE
        cd dist
        npm publish

  # publish-gpr:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@v2
  #     with:
  #       node-version: 16
  #       registry-url: https://npm.pkg.github.com/
  #   - run: npm ci
  #   - run: npm publish
  #     env:
  #       NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
