---

# Actions that take place on the main branch,
# driven by external dm-api events.

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# (n/a)
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (n/a)

name: publish

on:
  repository_dispatch:
    types:
      dm-api

env:
  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
  CI_PIPELINE_ID: ${{ github.event.client_payload.CI_PIPELINE_ID }}
  CI_COMMIT_TAG: ${{ github.event.client_payload.CI_COMMIT_TAG }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 16.4.0
    - name: Build and test
      run: |
        sed -i s/'"0.0.0"'/'"'${CI_COMMIT_TAG:-0.0.0}'"'/ package.json
        head package.json
        npm ci

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 16.4.0
        registry-url: https://registry.npmjs.org/
    - name: Publish
      run: |
        sed -i s/'"0.0.0"'/'"'${CI_COMMIT_TAG:-0.0.0}'"'/ package.json
        head package.json
        npm ci
        npm publish

  # publish-gpr:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@v2
  #     with:
  #       node-version: 16
  #       registry-url: https://npm.pkg.github.com/
  #   - run: npm ci
  #   - run: npm publish
  #     env:
  #       NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
