---
name: build

# Actions that take place on the main branch,
# pull-requests to the main branch and external dm-api events.

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# (n/a)
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (n/a)

on:
  repository_dispatch:
    types:
      dm-api
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 16.4.0
    - name: Build and test
      run: |
        sed -i s/'"0.0.0"'/'"'${CI_COMMIT_TAG:-0.0.0}'"'/ package.json
        head package.json
        npm ci
